// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: markfeedfetched.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markFetched = `-- name: MarkFetched :exec
UPDATE feeds
SET last_fetched_at = $1, updated_at = $1
WHERE feeds.id = $2
`

type MarkFetchedParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) MarkFetched(ctx context.Context, arg MarkFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFetched, arg.LastFetchedAt, arg.ID)
	return err
}
